FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

ARG WANDB_API_KEY=default_value

COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y


WORKDIR /root

RUN mkdir /root/results 
RUN mkdir /root/results/rlfold
RUN mkdir /root/rlfold
RUN mkdir /root/memory

ENV PYTHONPATH="/root/rlfold"
ENV RLFOLD_ROOT="/root/rlfold"

ENV USER="deep"
ENV WANDB_API_KEY=${WANDB_API_KEY}


